# Generated by Django 5.1.4 on 2025-02-17 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_days', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('drug', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('ascites', models.CharField(max_length=10)),
                ('hepatomegaly', models.CharField(max_length=10)),
                ('spiders', models.CharField(max_length=10)),
                ('edema', models.CharField(max_length=10)),
                ('bilirubin', models.FloatField()),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('albumin', models.FloatField()),
                ('copper', models.FloatField(blank=True, null=True)),
                ('alk_phos', models.FloatField(blank=True, null=True)),
                ('sgot', models.FloatField(blank=True, null=True)),
                ('tryglicerides', models.FloatField(blank=True, null=True)),
                ('platelets', models.FloatField()),
                ('prothrombin', models.FloatField()),
                ('prediction_result', models.IntegerField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
